### ISSUE TITLE
"failed to decrypt history! check your key: could not encrypt"  when attempting to connection third+ machines to Atuin

### ISSUE THREAD

**Issue by sawasy** [atuinsh/atuin#1664]
New install on Mint workstation
```
$ atuin -V
atuin 17.2.1

$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.2
DISTRIB_CODENAME=victoria
DISTRIB_DESCRIPTION="Linux Mint 21.2 Victoria"

$ grep -v -E "^#" .config/atuin/config.toml |sed -e '/^$/d'
sync_address = "https://atuin.my.inernal.dns.domain.goes.here"
enter_accept = true

$ zsh --version
zsh 5.8.1 (x86_64-debian-linux-gnu)

```

Installed in a Docker container using the docker compose YAML here: https://docs.atuin.sh/self-hosting/docker/
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

$ docker -v
Docker version 25.0.1, build 29cf629

$ docker compose version
Docker Compose version v2.24.2

$ docker compose logs
postgresql-1  | The files belonging to this database system will be owned by user "postgres".
postgresql-1  | This user must also own the server process.
postgresql-1  | 
postgresql-1  | The database cluster will be initialized with locale "en_US.utf8".
postgresql-1  | The default database encoding has accordingly been set to "UTF8".
postgresql-1  | The default text search configuration will be set to "english".
postgresql-1  | 
postgresql-1  | Data page checksums are disabled.
postgresql-1  | 
postgresql-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgresql-1  | creating subdirectories ... ok
postgresql-1  | selecting dynamic shared memory implementation ... posix
postgresql-1  | selecting default max_connections ... 100
postgresql-1  | selecting default shared_buffers ... 128MB
postgresql-1  | selecting default time zone ... Europe/London
postgresql-1  | creating configuration files ... ok
postgresql-1  | running bootstrap script ... ok
postgresql-1  | performing post-bootstrap initialization ... ok
postgresql-1  | syncing data to disk ... ok
postgresql-1  | 
postgresql-1  | 
postgresql-1  | Success. You can now start the database server using:
postgresql-1  | 
postgresql-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgresql-1  | 
postgresql-1  | initdb: warning: enabling "trust" authentication for local connections
postgresql-1  | You can change this by editing pg_hba.conf or using the option -A, or
postgresql-1  | --auth-local and --auth-host, the next time you run initdb.
postgresql-1  | waiting for server to start....2024-02-01 17:36:31.310 GMT [48] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgresql-1  | 2024-02-01 17:36:31.325 GMT [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql-1  | 2024-02-01 17:36:31.336 GMT [49] LOG:  database system was shut down at 2024-02-01 17:36:28 GMT
postgresql-1  | 2024-02-01 17:36:31.342 GMT [48] LOG:  database system is ready to accept connections
postgresql-1  |  done
postgresql-1  | server started
postgresql-1  | CREATE DATABASE
postgresql-1  | 
postgresql-1  | 
postgresql-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgresql-1  | 
postgresql-1  | waiting for server to shut down...2024-02-01 17:36:31.947 GMT [48] LOG:  received fast shutdown request
postgresql-1  | .2024-02-01 17:36:31.952 GMT [48] LOG:  aborting any active transactions
postgresql-1  | 2024-02-01 17:36:31.955 GMT [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgresql-1  | 2024-02-01 17:36:31.956 GMT [50] LOG:  shutting down
postgresql-1  | 2024-02-01 17:36:31.978 GMT [48] LOG:  database system is shut down
postgresql-1  |  done
postgresql-1  | server stopped
postgresql-1  | 
postgresql-1  | PostgreSQL init process complete; ready for start up.
postgresql-1  | 
postgresql-1  | 2024-02-01 17:36:32.077 GMT [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgresql-1  | 2024-02-01 17:36:32.077 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql-1  | 2024-02-01 17:36:32.077 GMT [1] LOG:  listening on IPv6 address "::", port 5432
postgresql-1  | 2024-02-01 17:36:32.081 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql-1  | 2024-02-01 17:36:32.099 GMT [63] LOG:  database system was shut down at 2024-02-01 17:36:31 GMT
postgresql-1  | 2024-02-01 17:36:32.105 GMT [1] LOG:  database system is ready to accept connections
```

Registering and syncing works no issues.

```
$ atuin status
Atuin v17.2.1 - Build rev 9f79a34a9dea207df7184972fa29f4fe5ec41b27

[Local]
Sync frequency: 10m
Last sync: 2024-02-01 18:41:25.718872828 +00:00:00
History count: 26682
Deleted history count: 0

[Remote]
Address: https://atuin.my.inernal.dns.domain.goes.here
Username: my.user.name
History count: 26668

```
I then setup another machine running Ubuntu 22.04 and had no issues.

I then tried to connect another 12 different machines and all received the following error:

```
$ atuin sync
0/0 up/down to record store
thread 'main' panicked at /home/runner/work/atuin/atuin/atuin-client/src/sync.rs:74:38:
failed to decrypt history! check your key: could not encrypt

Location:
    atuin-client/src/encryption.rs:132:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
The 12 servers are all running Ubuntu 22.04 or Debian 11.8. All clients are the same version of atuin as above.

On a broken host

```
➜ atuin status
Atuin v17.2.1 - Build rev 9f79a34a9dea207df7184972fa29f4fe5ec41b27

[Local]
Sync frequency: 10m
Last sync: 1970-01-01 0:00:00.0 +00:00:00
History count: 26416
Deleted history count: 0

[Remote]
Address: https://atuin.my.inernal.dns.domain.goes.here
Username: my.user.name
History count: 26673

$ sudo ntpstat
synchronised to NTP server (185.248.188.98) at stratum 2 
   time correct to within 33 ms
   polling server every 1024 s
```

**Comment by ellie** [comment]
Thank you!

I'll update the docs now, but could you add this to the env of the server?

```
RUST_LOG=info,atuin_server=debug
```

It can be super chatty so defaults to quiet

**Comment by sawasy** [comment]
After adding the parameters, I get the following on the docker container when connecting from a failing host:
```
atuin-1       | 2024-02-01T19:28:12.846270Z  INFO sqlx::postgres::notice: relation "_sqlx_migrations" already exists, skipping



atuin-1       | 2024-02-01T19:28:51.630388Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:51.713026Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:51.758848Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:51.798527Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:51.848561Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:51.900343Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:51.942338Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:51.981577Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.024343Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.071883Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.112950Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.151997Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.189202Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.224703Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.261770Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.299505Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.335732Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.373471Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.412416Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.470840Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.521429Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.612237Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.674991Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.710294Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T19:28:52.742176Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 312 items of history for user 1

```
And  the following when syncing from a working host:
```
atuin-1       | 2024-02-01T19:30:13.586092Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:13.796942Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:13.945715Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:14.108094Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:14.243798Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:14.392062Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:14.555121Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:14.555155Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 8197, max 8192
atuin-1       | 2024-02-01T19:30:14.699245Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:14.865884Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:15.005984Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:15.006011Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 15718, max 8192
atuin-1       | 2024-02-01T19:30:15.148282Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:15.299987Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:15.300019Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 10735, max 8192
atuin-1       | 2024-02-01T19:30:15.450988Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:15.451015Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 18568, max 8192
atuin-1       | 2024-02-01T19:30:15.451020Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 13621, max 8192
atuin-1       | 2024-02-01T19:30:15.593105Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:15.745146Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:15.882943Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:16.079722Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:16.079753Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 15287, max 8192
atuin-1       | 2024-02-01T19:30:16.079758Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 119729, max 8192
atuin-1       | 2024-02-01T19:30:16.221617Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:16.380850Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:16.380883Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 13732, max 8192
atuin-1       | 2024-02-01T19:30:16.538218Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:16.696366Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:16.828973Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:16.960269Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:17.100581Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T19:30:17.183594Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 290 history items

```


m!

**Comment by ellie** [comment]
ahhh!

That's super helpful, thank you.

```
atuin-1       | 2024-02-01T19:30:16.079753Z  WARN add{user.id=1}: atuin_server::handlers::history: history too long, got length 15287, max 8192
```

Is the issue here

Could you set

```
ATUIN_MAX_HISTORY_LENGTH: 0
```

and let me know if that resolves it?

For some background; we limit the maximum size of a history item by default. Seeing as Atuin just stores encrypted blobs, in theory they could be anything. The limit is in place to prevent abuse (think people using an Atuin server to store images or something)

Setting it to 0 will totally disable the size limit. If your server isn't open registration, then that's probably fine.

**Comment by sawasy** [comment]
No problem. Makes sense. This is a private setup, so I have no issues setting that param.  Doing so solved the error in the logs, as such:

```
atuin-1       | 2024-02-01T20:51:58.188285Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items       
atuin-1       | 2024-02-01T20:51:58.455807Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items       
atuin-1       | 2024-02-01T20:51:58.725881Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items       
atuin-1       | 2024-02-01T20:51:58.893482Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items       
atuin-1       | 2024-02-01T20:51:59.113754Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items       
atuin-1       | 2024-02-01T20:51:59.282909Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items       
atuin-1       | 2024-02-01T20:51:59.456829Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items       
atuin-1       | 2024-02-01T20:51:59.616004Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items      
atuin-1       | 2024-02-01T20:51:59.804288Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items
atuin-1       | 2024-02-01T20:51:59.958571Z DEBUG add{user.id=1}: atuin_server::handlers::history: request to add 1100 history items

```
But then when I try it again from a "broken" host, it failed unfortunately. 
This was the log output for the sync:
```
atuin-1       | 2024-02-01T20:52:19.632775Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:19.796953Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:19.961030Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:20.128851Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:20.294825Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:20.724189Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:20.891532Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:21.058994Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:21.222739Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:21.406477Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:21.587644Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:21.764065Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:21.930648Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:22.085158Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:22.246173Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:22.430259Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:22.749437Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:22.911571Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:23.078196Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:23.239752Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:23.388583Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:23.554927Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:23.725798Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:23.888271Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:24.039908Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 315 items of history for user 1
atuin-1       | 2024-02-01T20:52:24.316450Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:24.976791Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.020031Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.065040Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.110737Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.150339Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.194356Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.234294Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.272727Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.309987Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.346572Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.382133Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.419627Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.456487Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.492209Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.526472Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.561097Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.595073Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.628316Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.661605Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.693228Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.729957Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.761413Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.792679Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 1100 items of history for user 1
atuin-1       | 2024-02-01T20:52:25.821078Z DEBUG list{user.id=1}: atuin_server::handlers::history: loaded 315 items of history for user 1

```

m!

**Comment by ellie** [comment]
Is the value of `atuin key` the same on all machines? Alternatively, the `shasum` of `~/.local/share/atuin/key`?

Otherwise, please try the following and lmk what happens

1. Delete `~/.local/share/atuin` on a _broken_ host
2. Copy the entirety of `~/.local/share/atuin` from a _working_ host to the broken one
3. Run `atuin sync -f` on the broken host

Just checking to see if there's some sort of initial setup issue that's resolved by bootstrapping from a working setup

**Comment by sawasy** [comment]
Interesting.  `shasum ~/.local/share/atuin/key` showed them to be the same.

Copying the config from a working host did, however, work.  

Here are the contents of the directory on a broken host.
```
➜ ls -l .local/share/atuin
total 12476
-rw-r--r-- 1 mls mls 11419648 Feb  1 18:48 history.db
-rw-r--r-- 1 mls mls    32768 Feb  2 08:52 history.db-shm
-rw-r--r-- 1 mls mls  1256632 Feb  2 08:52 history.db-wal
-rw-rw-r-- 1 mls mls       32 Feb  1 18:25 host_id
-rw-rw-r-- 1 mls mls       76 Feb  2 08:51 key
-rw-rw-r-- 1 mls mls       30 Feb  2 08:52 last_version_check_time
-rw-rw-r-- 1 mls mls        6 Feb  2 08:52 latest_version
-rw-r--r-- 1 mls mls    36864 Feb  1 18:48 records.db
-rw-r--r-- 1 mls mls        0 Feb  2 08:52 records.db-wal
-rw-rw-r-- 1 mls mls       32 Feb  2 08:51 session
```

**Comment by ellie** [comment]
ok! that's good to know 

One more test - if you run

```
rm ~/.local/share/atuin/history*
```

and then

```
atuin sync -f
```

On the same host that _was_ broken before you copied it all across, is it broken once more?

**Comment by sawasy** [comment]
Yes, that recreated the error on the host I synced the settings over to.

```
atuin sync -f
0/0 up/down to record store
thread 'main' panicked at /home/runner/work/atuin/atuin/atuin-client/src/sync.rs:74:38:
failed to decrypt history! check your key: could not encrypt

Location:
    atuin-client/src/encryption.rs:132:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ellie** [comment]
Sorry for being slow here, was at FOSDEM all weekend.

I'm actually working on releasing the new sync as opt-in for v18 this week. If you're OK to wait for that, that would be amazing.

Otherwise if you'd like to try it out now, there are instructions here: https://forum.atuin.sh/t/sync-v2-testing/124

**Comment by sawasy** [comment]
Sure. 
I updated the docker image to 8372abb.  
To `~/.config/atuin/config.toml` I added
```
[sync]
records = true
```
On a 'working' host running 17.2.1, it worked.  However, on a 'broken' host, it still throws the encrypt error.
```
$ atuin logout; atuin login -u <USERID> -p <PASSWORD> -k "<KEY>"; atuin sync
You have logged out!
Logged in!
0/0 up/down to record store

thread 'main' panicked at /home/runner/work/atuin/atuin/atuin-client/src/sync.rs:74:38:
failed to decrypt history! check your key: could not encrypt

Location:
    atuin-client/src/encryption.rs:132:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ tail -2 ~/.config/atuin/config.toml
[sync]
records = true
$atuin -V
17.2.1
```

m!

**Comment by ellie** [comment]
> On a 'working' host running 17.2.1

You'll also need to update the clients to the latest `main` btw

**Comment by ellie** [comment]
Ah sorry I should have made this clearer!

Three options, use whichever

1. From the docs (clone repo and build): https://docs.atuin.sh/guide/installation/#from-source
2. Run this `cargo install --git https://github.com/atuinsh/atuin.git`
3. I've kicked off a build here, so you can download a binary: https://github.com/atuinsh/atuin/actions/runs/7790333447

**Comment by sawasy** [comment]
Okay. For my sanity, the above three client installations will show as version 17.2.1, correct?

m!

**Comment by ellie** [comment]
That's correct! It's still the version set in cargo.toml, until we release v18

**Comment by sawasy** [comment]
That seems to work. I'm testing on more systems, but the previously 'broken' client is now syncing.

m!

**Comment by ellie** [comment]
Excellent! Glad to hear it 🙏 

If you ever get anything about an unknown key again, let me know - record sync has a bunch of maintenance commands we can use to workaround it

**Comment by sawasy** [comment]
Sure, I'll let you know if that crops up again. Perhaps you can answer a question for me.  All of the clients show the following:
```
[Remote]
Address: https://atuin.my.domain
Username: $username
History count: 36040
```
The history count doesn't increase.  Is that normal behaviour? I would think the server side history should keep increasing?

m!

**Comment by ellie** [comment]
> The history count doesn't increase. Is that normal behaviour?

It is - it's syncing via a different route now, which still needs a _little_ polishing before general use. 

Stick with `atuin store status` for now

**Comment by sawasy** [comment]
Will do. Thanks for you help on this.

m!
