### ISSUE TITLE
Panic when copying on a system not running X

### ISSUE THREAD

**Issue by ellie** [atuinsh/atuin#1707]
See more details:

https://forum.atuin.sh/t/error-when-copying-to-clipboard-without-x-server/157

# Replication steps

- Run on a machine without X (eg, SSH into a server)
- ctrl-y on a history item to yank to clipboard
- observe panic

```
thread 'main' panicked at atuin/src/command/client/search/interactive.rs:1013:36:
called `Result::unwrap()` on an `Err` value: XcbConnect(DisplayParsingError)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Expected behaviour

Atuin should do nothing in an environment without a clipboard

**Comment by halostatue** [comment]
Adding support for [OSC 52](https://www.reddit.com/r/vim/comments/k1ydpn/a_guide_on_how_to_copy_text_from_anywhere/) might be useful for some cases, although it depends on the terminal application (I just learned about this, so…).

**Comment by wudi** [comment]
same issue

### Environment

MacOS 14.2.1
iTerm2 Build 3.5.0beta19
zsh zsh 5.8 (x86_64-debian-linux-gnu)
atuin 17.2.1

### Steps
same as ellie


### Backtrace
```
[root@contabo-USW1] ~
❯ thread 'main' panicked at atuin/src/command/client/search/interactive.rs:719:42:
called `Result::unwrap()` on an `Err` value: XcbConnect(DisplayParsingError)
stack backtrace:
   0:     0x557f96be5adc - <unknown>
   1:     0x557f96c14c60 - <unknown>
   2:     0x557f96be232f - <unknown>
   3:     0x557f96be58c4 - <unknown>
   4:     0x557f96be6ec7 - <unknown>
   5:     0x557f96be6c2f - <unknown>
   6:     0x557f96be7348 - <unknown>
   7:     0x557f96be722e - <unknown>
   8:     0x557f96be5fa6 - <unknown>
   9:     0x557f96be6f92 - <unknown>
  10:     0x557f9601c3e5 - <unknown>
  11:     0x557f9601c923 - <unknown>
  12:     0x557f960c4bdc - <unknown>
  13:     0x557f960d9160 - <unknown>
  14:     0x557f960daef0 - <unknown>
  15:     0x557f9617ecd7 - <unknown>
  16:     0x557f9602f07b - <unknown>
  17:     0x557f9625caf3 - <unknown>
  18:     0x557f9612930d - <unknown>
  19:     0x557f96bd9dc7 - <unknown>
  20:     0x557f961292fe - <unknown>
  21:     0x7fbe121cbd0a - __libc_start_main
  22:     0x557f9601cc2e - <unknown>
  23:                0x0 - <unknown>
zsh: parse error near `\n'
```

**Comment by jonasgeiler** [comment]
Same problem here on a clean Debian 12 installation over SSH... Let me know if you need details.

**Comment by dhth** [comment]
@ellie 
Sent in a tiny change for this. Have a few follow up questions in the [PR](https://github.com/atuinsh/atuin/pull/2648).

Thanks.
