### ISSUE TITLE
sync -f "Failed to decrypt history!" error

### ISSUE THREAD

**Issue by plars** [atuinsh/atuin#1850]
I'm trying to sync history between two different devices and wasn't seeing the same history on each. Both are logged into the same account successfully.
I registered the account on one device, then logged into a second device. On the second device, I synced history, then on the first I synced history, but they still only see their *own* history - not the other.
So I decided to try `atuin sync -f` and got this error:
```
thread 'main' panicked at /tmp/atuin-20240226-9218-rw12ap/atuin-18.0.2/atuin-client/src/sync.rs:74:38:
failed to decrypt history! check your key: could not encrypt

Location:
    atuin-client/src/encryption.rs:143:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here's the output with backtrace enabled:
```
thread 'main' panicked at /tmp/atuin-20240226-9218-rw12ap/atuin-18.0.2/atuin-client/src/sync.rs:74:38:
failed to decrypt history! check your key: could not encrypt

Location:
    atuin-client/src/encryption.rs:143:22
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: atuin_client::sync::sync::{{closure}}
   6: atuin::command::client::Cmd::run_inner::{{closure}}
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: atuin::command::AtuinCmd::run
  11: atuin::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by plars** [comment]
fwiw, I sorted out that I needed to run `atuin store rekey` and specify the key of the other one so that they are using the same key now. But it still might be worth catching that error and giving some nicer output

**Comment by ellie** [comment]
Glad you got it sorted! Sync v2 should handle this a bit better, opt in with

```
[sync]
records = true
```

and run `atuin sync`
