### ISSUE TITLE
RFE: Testing postgres 

### ISSUE THREAD

**Issue by LecrisUT** [atuinsh/atuin#2066]
Right now if I run the default `cargo test --workspace --all-features` I get failures with postgres tests.

<details><summary>Example</summary>

```console
ERROR sync::common server error, error=failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:pass@localhost:5432/atuin" }

Caused by:
    Other(pool timed out while waiting for an open connection

    Location:
        atuin-server-postgres/src/lib.rs:34:39)

Location:
    /home/lecris/RustroverProjects/atuin/atuin-server/src/lib.rs:141:10

called `Result::unwrap()` on an `Err` value: error sending request for url (http://127.0.0.1:46805/018fcde9a2c77e8fab5079608bb73b6e/user/018fcde9a398735f9e7d369901984f51): connection error: Connection reset by peer (os error 104)

Caused by:
   0: connection error: Connection reset by peer (os error 104)
   1: Connection reset by peer (os error 104)

Location:
    /home/lecris/RustroverProjects/atuin/atuin-client/src/api_client.rs:49:16
thread 'sync' panicked at atuin/tests/common/mod.rs:57:13:
error running server: failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:pass@localhost:5432/atuin" }

Caused by:
    Other(pool timed out while waiting for an open connection

    Location:
        atuin-server-postgres/src/lib.rs:34:39)

Location:
    /home/lecris/RustroverProjects/atuin/atuin-server/src/lib.rs:141:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: sync::common::start_server::{{closure}}::{{closure}}
             at ./tests/common/mod.rs:57:13
   3: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
   4: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
   5: tokio::runtime::task::core::Core<T,S>::poll
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
   6: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
   7: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
   8: std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
   9: __rust_try
  10: std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  11: std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  12: tokio::runtime::task::harness::poll_future
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  13: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  14: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  15: tokio::runtime::task::raw::poll
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271:5
  16: tokio::runtime::task::raw::RawTask::poll
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  17: tokio::runtime::task::LocalNotified<S>::run
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:427:9
  18: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:700:25
  19: tokio::runtime::coop::with_budget
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  20: tokio::runtime::coop::budget
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  21: tokio::runtime::scheduler::current_thread::Context::run_task::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:343:43
  22: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:404:19
  23: tokio::runtime::scheduler::current_thread::Context::run_task
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:343:23
  24: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:699:35
  25: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:737:68
  26: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  27: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:284:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:260:9
  30: tokio::runtime::context::set_scheduler
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:9
  31: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:737:27
  32: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:646:19
  33: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  34: tokio::runtime::context::runtime::enter_runtime
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  35: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  36: tokio::runtime::runtime::Runtime::block_on
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/runtime.rs:349:47
  37: sync::sync
             at ./tests/sync.rs:44:5
  38: sync::sync::{{closure}}
             at ./tests/sync.rs:7:16
  39: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  40: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'sync' panicked at atuin/tests/common/mod.rs:77:10:
called `Result::unwrap()` on an `Err` value: error sending request for url (http://127.0.0.1:46805/018fcde9a2c77e8fab5079608bb73b6e/user/018fcde9a398735f9e7d369901984f51): connection error: Connection reset by peer (os error 104)

Caused by:
   0: connection error: Connection reset by peer (os error 104)
   1: Connection reset by peer (os error 104)

Location:
    /home/lecris/RustroverProjects/atuin/atuin-client/src/api_client.rs:49:16
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
   4: sync::common::register_inner::{{closure}}
             at ./tests/common/mod.rs:75:33
   5: sync::common::register::{{closure}}
             at ./tests/common/mod.rs:99:51
   6: sync::sync::{{closure}}
             at ./tests/sync.rs:11:45
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:659:57
  10: tokio::runtime::coop::with_budget
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:659:25
  13: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:404:19
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:658:36
  15: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:737:68
  16: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  17: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  18: std::thread::local::LocalKey<T>::try_with
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:284:16
  19: std::thread::local::LocalKey<T>::with
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:260:9
  20: tokio::runtime::context::set_scheduler
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:9
  21: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:737:27
  22: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:646:19
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  24: tokio::runtime::context::runtime::enter_runtime
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  25: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  26: tokio::runtime::runtime::Runtime::block_on
             at /home/lecris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/runtime.rs:349:47
  27: sync::sync
             at ./tests/sync.rs:44:5
  28: sync::sync::{{closure}}
             at ./tests/sync.rs:7:16
  29: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

I see that in the github actions, a postgres server is setup, but I want to confirm how the server is setup. Is it just an empty database created? I would like to make sure the tests are as complete as possible on Fedora side, and would appreciate some help understanding the setup there.

In principle there are 2 orthogonal ways that this can be approached:
- On upstream using some mocking library to mock the postgres server
- On downstream we can make arbitrary setups for full integration/regression tests. Just need a bit of guidance on what should be setup and how to trigger such tests in the pre-comipled binary (or if it requires running the whole build again)

**Comment by ellie** [comment]
The tests only require an empty database, and a user with permission to create tables/etc. Migrations are ran at startup

> On upstream using some mocking library to mock the postgres server

We won't be doing this one however - I'm not that keen on requiring a database for the full test suite, but mocks are not a suitable replacement.

> Just need a bit of guidance on what should be setup and how to trigger such tests in the pre-comipled binary

There's no way to run these tests from a `atuin` binary, using `cargo test` would be the recommended approach

**Comment by LecrisUT** [comment]
Ok got some feedback from other devs on how to approach this and we'll go with the downstream setup approach. I'll be tracking the setup for Fedora [here](https://github.com/SriRamanujam/atuin-rpmspec/issues/10).
